import type { Metadata } from "next";
import { Inter } from "next/font/google"; // Import Google Fonts for styling
import Header from "@/components/Header"; // Import Header component
import Footer from "@/components/Footer"; // Import Footer component
import "./globals.css"; // Import global CSS styles

// Initialize Inter font with Latin subset
const inter = Inter({ subsets: ["latin"] });

// Metadata for the page (optional)
export const metadata: Metadata = {
  title: "Logic IT Center", // Set the title for your website
  description: "Generated by create next app", // Set the description for your website
};

// Root layout function that will wrap your content
export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        {/* You can add meta tags here for SEO, or other head elements */}
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body className={inter.className}>
        {/* Header Component */}
        <Header />
        
        {/* Content Section */}
        <div className="overflow-x-hidden">
          {children}
        </div>
        
        {/* Footer Component */}
        <Footer />
      </body>
    </html>
  );
}
